#
# This docker compose file installs the Community Edition of PAYLAY on your local dev machine.
# For production purposes, please put all containers behind a Reverse Proxy with SSL.
#
# After completion you should be able to access the following endpoints from your browser.
#
# PaymentServer Swagger
# http://localhost:28888/swagger
#
# Dashboard
# http://localhost:28889
#
# IdentityServer discovery endpoint
# http://localhost:28890/.well-known/openid-configuration
#
version: '3.3'

services:
  # identityserver_install:
  #   image: paylay/identityserver:latest
  #   volumes:
  #     - ${PAYLAY_DIR}:/var/tmp/paylay
  #   command: ["install", "--accept-eula"]
  #   restart: "no"
  #   environment:
  #     paylay:identityserver:connectionstring: Data Source=/var/tmp/paylay/identityserver.sqlite
  #     paylay:identityserver:rdbms: sqlite
  #     paylay:identityserver:signingcertificate:path: /var/tmp/paylay/identityserver-signing.p12
  #     paylay:identityserver:signingcertificate:password: helloworld

  identityserver:
    # depends_on:
    #   - identityserver_install
    image: paylay/identityserver:latest
    ports:
      - "28890:28890"
    volumes:
      - ${PAYLAY_DIR}:/var/tmp/paylay
    command: ["run"]
    restart: always
    environment:
      urls: http://*:28890
      logging:loglevel:microsoft: debug
      paylay:identityserver:connectionstring: Data Source=/var/tmp/paylay/identityserver.sqlite
      paylay:identityserver:rdbms: sqlite
      paylay:identityserver:signingcertificate:path: /var/tmp/paylay/identityserver-signing.p12
      paylay:identityserver:signingcertificate:password: helloworld
  
  paymentserver:
    depends_on:
      - identityserver
    image: paylay/paymentserver:latest
    ports:
      - "28888:28888"
    volumes:
      - ${PAYLAY_DIR}:/var/tmp/paylay
    restart: always
    environment:
      paylay:paymentserver:connectionstring: Data Source=/var/tmp/paylay/paymentserver.sqlite
      paylay:paymentserver:rdbms: sqlite
      paylay:paymentserver:authentication:authority: http://host.docker.internal:28890

  dashboard:
    depends_on:
      - identityserver
      - paymentserver
    image: paylay/dashboard:latest
    ports:
      - "28889:28889"
    links:
      - "identityserver"
      - "paymentserver"
    command: ["run"]
    restart: always
    environment:
      urls: http://*:28889
      logging:loglevel:microsoft: debug
      paylay:dashboard:paymentserver:uri: http://paymentserver:28888
      paylay:dashboard:authentication:authority: http://identityserver:28890
      paylay:dashboard:authentication:clientid: dashboard
      paylay:dashboard:authentication:clientsecret: dashboard
      paylay:dashboard:authentication:requirehttpsmetadata: "false"
      paylay:dashboard:authentication:onredirecttoidentityprovider:authority: http://localhost:28890