remote_theme: pmarsceill/just-the-docs

title: PAYLAY Documentation

url: "https://docs.paylay.io"

logo: "/images/paylay-logo-100x100.png"

footer_content: "Copyright &copy; 2019 PAYLAY International B.V."